import { State } from "../Models/State";
import { Unit, makeUnit } from "../Models/Entities/Unit";
import { pickRandom } from "../utils";
import * as Card from "../Models/Entities/Card";
import * as BoardLogic from "../Models/BoardLogic";
import { generateEnemyTeam } from "../Scenes/Battleground/generateEnemyTeam";
import { runCombat } from "../Scenes/Battleground/RunCombatCore";
import { createServerCombatEffects } from "../Scenes/Battleground/ServerCombatEffects";
import { FORCE_ID_PLAYER, FORCE_ID_CPU } from "../Scenes/Battleground/ServerConstants";
import { makeForce } from "../Models/Entities/Force";
import { BASE_COLLECTION_DATA } from "../Data/BaseCollection";
import { registerCollection } from "../Models/Entities/Card";
import * as Random from "../Utils/Random";

// Register base collection to ensure unit definitions exist
registerCollection(BASE_COLLECTION_DATA);

const ENCOUNTER_IDS = [
	'upgrade_unit',
	'armory',
	'healing_tent',
	'frontier_fort',
	'forest_pools',
	'toxic_chamber',
	'trial_circuit',
	'trappers_guild',
	'thunder_spire',
	'commanders_tent',
	'assassins_hideout',
	'power_distributor',
	'power_absorber',
	'silver_shop',
	'gold_shop'
];

export interface SessionData {
	id: string;
	player_id: string;
	phase: string;
	round: number;
	step: number;
	seed: string;
	initial_seed: string;
	action_log: any[];
	current_options?: any[];
	wins: number;
	losses: number;
	team?: any;
	updated_at?: Date;
}

export class MultiplayerLogic {
	public static createInitialSession(playerId: string, selectedCrystalId?: string): SessionData {
		const seed = Math.random().toString(36).substring(7);
		const initialSeed = seed;

		let team: any = { units: [] };
		if (selectedCrystalId) {
			const coreUnit = makeUnit(FORCE_ID_PLAYER, selectedCrystalId, { x: 1, y: 1 });
			coreUnit.isCore = true;
			team.units.push(coreUnit);
		}

		const session: SessionData = {
			id: '', // Will be generated by DB
			player_id: playerId,
			phase: 'encounter',
			round: 1,
			step: 1,
			seed,
			initial_seed: initialSeed,
			action_log: [],
			wins: 0,
			losses: 0,
			team
		};

		const options = this.generateEncounterOptions(session);
		session.current_options = options.options;

		return session;
	}

	public static generateEnemyTeamForRound(round: number, wins: number): any[] {
		// CPU should have access to all non-core units, disregarding unlock status
		const allCards = Card.getNonCores();
		const mockState = {
			battleData: { forces: [makeForce(FORCE_ID_PLAYER), makeForce(FORCE_ID_CPU)] },
			gameData: { player: { wins, id: FORCE_ID_PLAYER } }
		} as any;
		const units = generateEnemyTeam(mockState, round, allCards);
		// Explicitly assign to CPU force to ensure correctness regardless of mock state nuances
		units.forEach(u => u.force = FORCE_ID_CPU);
		return units;
	}

	public static stringToSeed(str: string): number {
		let hash = 0;
		for (let i = 0; i < str.length; i++) {
			const char = str.charCodeAt(i);
			hash = ((hash << 5) - hash) + char;
			hash = hash & hash;
		}
		return Math.abs(hash);
	}

	public static generateNextSeed(currentSeed: string, actionId: string): string {
		const input = currentSeed + actionId;
		let hash = 0;
		for (let i = 0; i < input.length; i++) {
			const char = input.charCodeAt(i);
			hash = ((hash << 5) - hash) + char;
			hash = hash & hash;
		}
		return Math.abs(hash).toString(36);
	}

	public static generateEncounterOptions(session: SessionData): { options: any[], nextPhase?: string } {
		if (session.step === 7) {
			return { options: [{ id: 'combat_encounter' }] };
		}

		const seedNum = this.stringToSeed(session.seed);
		const shuffled = [...ENCOUNTER_IDS];
		let currentSeedVal = seedNum;

		for (let i = shuffled.length - 1; i > 0; i--) {
			const x = Math.sin(currentSeedVal++) * 10000;
			const rnd = x - Math.floor(x);
			const j = Math.floor(rnd * (i + 1));
			[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
		}

		return { options: shuffled.slice(0, 3).map(id => ({ id })) };
	}

	public static generateShopOptions(session: SessionData, triggerActionId?: string): { options: any[] } {
		let encounterId = null;

		if (triggerActionId) {
			encounterId = triggerActionId;
		} else {
			const previousStep = session.step - 1;
			const lastEncounterAction = session.action_log.find((a: any) => a.round === session.round && a.step === previousStep);
			encounterId = lastEncounterAction ? lastEncounterAction.actionId : null;
		}

		let filterType = "";
		if (encounterId) {
			if (encounterId === 'armory') filterType = 'damage';
			else if (encounterId === 'healing_tent') filterType = 'heal';
			else if (encounterId === 'frontier_fort') filterType = 'shield';
			else if (encounterId === 'forest_pools') filterType = 'regen';
			else if (encounterId === 'toxic_chamber') filterType = 'poison';
			else if (encounterId === 'trial_circuit') filterType = 'haste';
			else if (encounterId === 'trappers_guild') filterType = 'slow';
			else if (encounterId === 'thunder_spire') filterType = 'charge';
			else if (encounterId === 'commanders_tent') filterType = 'increase_power';
			else if (encounterId === 'assassins_hideout') filterType = 'increase_critical';
			else if (encounterId === 'silver_shop') filterType = 'silver';
			else if (encounterId === 'gold_shop') filterType = 'gold';
		}

		const allCards = Card.getNonCores();
		let filteredCards = allCards;

		if (filterType) {
			if (filterType === 'silver') {
				filteredCards = allCards.filter(card => card.rank === 2);
			} else if (filterType === 'gold') {
				filteredCards = allCards.filter(card => card.rank === 3);
			} else {
				filteredCards = allCards.filter(card =>
				(card.effects?.some(eff => eff.id === filterType) ||
					card.reactions?.some(react => react.effects?.some(eff => eff.id === filterType)))
				);
			}
		}

		if (filteredCards.length === 0) {
			filteredCards = allCards;
		}

		const options = pickRandom(filteredCards, 3).map(card => ({
			id: card.id,
			cost: 10
		}));

		return { options };
	}

	public static resolveAction(session: SessionData, actionId: string, payload?: any): { team: any, updates?: string[] } {
		// Returns modified team object
		const availableCards = Card.getNonCores();
		const card = availableCards.find(c => c.id === actionId);

		let team = session.team ? JSON.parse(JSON.stringify(session.team)) : { units: [] };
		let units = team.units || [];
		const updates: string[] = [];

		if (card) {
			const existingUnitIndex = units.findIndex((u: any) => u.cardId === actionId);
			if (existingUnitIndex >= 0) {
				const existingUnit = units[existingUnitIndex];
				if (existingUnit.rank < 4) {
					existingUnit.rank++;
					existingUnit.maxLife = Math.floor(existingUnit.maxLife * 1.5);
					existingUnit.life = existingUnit.maxLife;
					existingUnit.power = Math.floor(existingUnit.power * 1.5);
					updates.push(`Upgraded unit ${actionId} to rank ${existingUnit.rank}`);
				}
			} else {
				if (units.length < 9) {
					const targetPos = BoardLogic.getEmptySlot(units, FORCE_ID_PLAYER);
					if (targetPos) {
						const newUnit = makeUnit(FORCE_ID_PLAYER, actionId, targetPos);

						// Silver/Gold Shop Context Logic
						const previousStep = session.step - 1;
						const lastEncounterAction = session.action_log.find((a: any) => a.round === session.round && a.step === previousStep);
						const encounterId = lastEncounterAction ? lastEncounterAction.actionId : null;
						let targetRank = 1;
						if (encounterId === 'silver_shop') targetRank = 2;
						if (encounterId === 'gold_shop') targetRank = 3;

						if (targetRank > 1) {
							newUnit.rank = targetRank;
							const extraLevels = targetRank - 1;
							for (let i = 0; i < extraLevels; i++) {
								newUnit.maxLife = Math.floor(newUnit.maxLife * 1.5);
								newUnit.life = newUnit.maxLife;
								newUnit.power = Math.floor(newUnit.power * 1.5);
							}
							updates.push(`Recruited unit ${actionId} at Rank ${newUnit.rank}`);
						}

						units.push(newUnit);
						updates.push(`Added new unit ${actionId}`);
					}
				}
			}
		} else {
			// Orb/Encounter Logic
			if (actionId === 'apply_orb' && payload) {
				const { orbId, targetUnitId } = payload;
				const targetUnit = units.find((u: any) => u.id === targetUnitId);
				if (targetUnit) {
					updates.push(`Applying orb ${orbId} to ${targetUnitId}`);
					if (payload.orbId === 'upgrade_orb') {
						targetUnit.rank = (targetUnit.rank || 1) + 1;
						targetUnit.maxLife = Math.floor(targetUnit.maxLife * 1.5);
						targetUnit.life = targetUnit.maxLife;
						targetUnit.power = Math.floor(targetUnit.power * 1.5);
					} else if (payload.orbId === 'absorb_power_orb') {
						let totalAbsorbed = 0;
						units.forEach((u: any) => {
							if (u.id !== targetUnit.id && u.position && u.position.y === targetUnit.position.y) {
								const absorbed = Math.floor(u.power * 0.25);
								if (absorbed > 0) {
									u.power = Math.max(0, u.power - absorbed);
									totalAbsorbed += absorbed;
								}
							}
						});
						if (totalAbsorbed > 0) {
							targetUnit.power = (targetUnit.power || 0) + totalAbsorbed;
							targetUnit.bonusPower = (targetUnit.bonusPower || 0) + totalAbsorbed;
						}
					} else if (payload.orbId === 'distribute_power_orb') {
						const powerToDistribute = Math.floor(targetUnit.power * 0.5);
						if (powerToDistribute > 0) {
							targetUnit.power = Math.max(0, targetUnit.power - powerToDistribute);
							const bonusToLose = Math.max(0, Math.min(targetUnit.bonusPower || 0, powerToDistribute));
							targetUnit.bonusPower = (targetUnit.bonusPower || 0) - bonusToLose;

							const targets = units.filter((u: any) => u.id !== targetUnit.id && u.position && u.position.y === targetUnit.position.y);
							if (targets.length > 0) {
								const powerPerTarget = Math.floor(powerToDistribute / targets.length);
								targets.forEach((u: any) => {
									u.power = (u.power || 0) + powerPerTarget;
									u.bonusPower = (u.bonusPower || 0) + powerPerTarget;
								});
							}
						}
					} else if (payload.orbId.startsWith('increase_power_on_')) {
						const type = payload.orbId.replace('increase_power_on_', '');
						if (targetUnit.effects?.some((e: any) => e.id === type)) {
							const pct = Math.floor(targetUnit.power * 0.1);
							targetUnit.power += pct;
							updates.push(`Increased power of ${targetUnit.id} by ${pct} (on ${type})`);
						}
					} else if (payload.orbId.startsWith('increase_critical_on_')) {
						const type = payload.orbId.replace('increase_critical_on_', '');
						if (targetUnit.effects?.some((e: any) => e.id === type)) {
							targetUnit.effects = targetUnit.effects || [];
							targetUnit.effects.push({ id: 'increase_critical', amount: 10, targets: { id: 'self' } });
							updates.push(`Increased critical of ${targetUnit.id} (on ${type})`);
						}
					} else if (payload.orbId.startsWith('decrease_cooldown_on_')) {
						const type = payload.orbId.replace('decrease_cooldown_on_', '');
						if (targetUnit.effects?.some((e: any) => e.id === type)) {
							targetUnit.cooldown = Math.max(1000, targetUnit.cooldown * 0.9);
							updates.push(`Decreased cooldown of ${targetUnit.id} (on ${type})`);
						}
					}
				}
			} else if (actionId === 'discard_unit' && payload && payload.unitId) {
				const unitIndex = units.findIndex((u: any) => u.id === payload.unitId);
				if (unitIndex >= 0) {
					const unit = units[unitIndex];
					if (!unit.isCore) {
						units.splice(unitIndex, 1);
						updates.push(`Discarded unit ${payload.unitId}`);
					}
				}
			}
		}

		team.units = units;
		return { team, updates };
	}

	public static validateAndApplyTeamUpdate(session: SessionData, newTeam: any): { team: any, valid: boolean } {
	// Only allow position updates. Prevent adding/removing/upgrading units via this endpoint.
	const currentUnits = session.team?.units || [];
	const newUnits = newTeam?.units || [];

	if (currentUnits.length !== newUnits.length) {
		return { team: session.team, valid: false };
	}

	// Create a map of current units for verification
	const currentUnitMap = new Map();
	currentUnits.forEach((u: any) => currentUnitMap.set(u.id, u));

	const validatedUnits = [];

	for (const newUnit of newUnits) {
		const originalUnit = currentUnitMap.get(newUnit.id);
		if (!originalUnit) {
			// Unit ID mistmatch - potential cheating or sync error
			return { team: session.team, valid: false };
		}

		// Check if critical stats match (prevent stats hacking)
		if (originalUnit.cardId !== newUnit.cardId ||
			originalUnit.rank !== newUnit.rank) {
			return { team: session.team, valid: false };
		}

		// Allow position update
		// We construct a new unit object using critical data from Server + Position from Client
		const validatedUnit = {
			...originalUnit,
			position: newUnit.position // Acceptance of client position
		};
		validatedUnits.push(validatedUnit);
	}

	return { team: { units: validatedUnits }, valid: true };
}

	public static simulateCombat(session: SessionData): { finalState: State, initialUnits: Unit[], logs: any[] } {
	const combatState = this.createCombatState(session);

	// Ensure RNG is seeded for deterministic simulation
	const seedVal = this.stringToSeed(session.initial_seed);
	Random.setSeed(seedVal);

	const initialUnits = JSON.parse(JSON.stringify(combatState.battleData.units));

	const effects = createServerCombatEffects(combatState);
	const combatRunner = runCombat(combatState, effects);

	const SIM_DELTA = 16.67;
	let frame = 0;
	const MAX_FRAMES = 10000;
	while (combatRunner.isActive() && frame < MAX_FRAMES) {
		effects.setFrame(frame);
		combatRunner.updateFrame(combatState, frame * SIM_DELTA, SIM_DELTA);
		frame++;
	}

	return { finalState: combatState, initialUnits, logs: effects.logs };
}

	private static createCombatState(session: SessionData): State {
	let playerUnits: Unit[] = [];
	if (session.team && (session.team as any).units) {
		playerUnits = JSON.parse(JSON.stringify((session.team as any).units));
		playerUnits.forEach(u => {
			u.effects = u.effects || [];
			u.reactions = u.reactions || [];
			u.life = u.maxLife;
		});
	}

	const hasCore = playerUnits.some(u => u.isCore);
	if (!hasCore) {
		const freeSlot = BoardLogic.findFreeSlot(playerUnits, FORCE_ID_PLAYER, { x: 1, y: 1 });
		if (freeSlot) {
			const crystal = makeUnit(FORCE_ID_PLAYER, "crystal_core", freeSlot);
			crystal.isCore = true;
			playerUnits.push(crystal);
		}
	}

	let enemyUnits: Unit[] = [];
	if (session.current_options && (session.current_options as any).combatState && (session.current_options as any).combatState.enemyTeam) {
		enemyUnits = JSON.parse(JSON.stringify((session.current_options as any).combatState.enemyTeam));
	} else {
		const allCards = Card.getNonCores();
		const mockState = {
			battleData: { forces: [makeForce(FORCE_ID_PLAYER), makeForce(FORCE_ID_CPU)] },
			gameData: { player: { wins: session.wins || 0, id: FORCE_ID_PLAYER } }
		} as any;
		enemyUnits = generateEnemyTeam(mockState, session.round, allCards);
		enemyUnits.forEach(u => u.force = FORCE_ID_CPU);
	}

	return {
		savedGames: [],
		gameData: {
			round: session.round,
			hour: 0,
			player: makeForce(FORCE_ID_PLAYER),
			recentEncounterIds: [],
			runStats: {} as any,
			seed: this.stringToSeed(session.initial_seed),
			initialSeed: this.stringToSeed(session.initial_seed),
			isSeeded: true
		},
		battleData: {
			forces: [makeForce(FORCE_ID_PLAYER), makeForce(FORCE_ID_CPU)],
			grid: BoardLogic.createGrid(),
			units: [...playerUnits, ...enemyUnits]
		}
	};
}
	public static processSessionTurn(
	session: SessionData,
	actionId: string,
	payload ?: any
): { session: SessionData; updates: string[] | undefined; combatResult ?: { won: boolean } } {
	// 1. Resolve Action (Team Updates)
	const { team, updates } = this.resolveAction(session, actionId, payload);
	let nextSession = { ...session, team };
	let combatResult = undefined;

	// 2. Handle Combat Phase Processing (if we are currently in combat and finishing it)
	if (nextSession.phase === 'combat' && actionId === 'combat_done') {
		// Combat is done, move to next round
		// Logic handled below in "Advance Phase"
	} else if (nextSession.phase === 'combat') {
		// specific combat actions if any? 
		// For now, if phase is combat, we expect 'combat_done' to proceed.
		// But wait, the server logic triggered combat processing *before* returning to client.
		// The client calls 'combat_done' to acknowledge.
	}

	// 3. Game Loop / State Machine
	// 3. Game Loop / State Machine
	// const newSeed = this.generateNextSeed(nextSession.seed, actionId);

	// If we are currently in combat, processing 'combat_done' moves us to next round
	if (nextSession.phase === 'combat' && actionId === 'combat_done') {
		// We already calculated wins/losses when entering combat phase (see below).
		// So we just reset to step 1 of next round.

		// But wait, looking at action/index.ts:
		// It calculates result WHEN calling 'combat', then updates wins/losses and invokes `increment_rating`.
		// Then it waits for 'combat_done'.

		// Actually action/index.ts line 95: if (session.phase === 'combat') ...
		// This block runs when the USER sends an action while the session IS IN combat phase.
		// Currently the only action sent during combat phase (from client) is likely 'combat_done' (or nothing if auto?).
		// Check action/index.ts logic again.
	}

	return { session: nextSession, updates, combatResult };
}

	// Helper to encapsulate the complex transition logic
	public static transitionToNextState(session: SessionData, actionId: string, payload ?: any): { session: SessionData, combatResult ?: { won: boolean } } {
	const nextSession = JSON.parse(JSON.stringify(session)); // Deep copy

	// If we are already in combat phase, we are waiting for 'combat_done' to proceed to next round
	if (nextSession.phase === 'combat') {
		// Transition handling is actually done *before* entering this state in the previous turn?
		// No, typically:
		// 1. User is in 'encounter' (step 6).
		// 2. User sends action (e.g., 'upgrade_unit').
		// 3. Server resolves action.
		// 4. Server sees step 6 -> 7. Step 7 is Combat.
		// 5. Server performs simulation, updates DB with 'combat' phase and results. RETURNS result to client.
		// 6. Client plays combat.
		// 7. Client sends 'combat_done'.
		// 8. Server receives 'combat_done'. Server updates DB to Round + 1, Step 1.

		if (actionId === 'combat_done') {
			// Determine next phase based on wins/losses (already updated when entering combat?)
			// looking at action/index.ts:
			// It updates wins/losses immediately when resolving the combat simulation. 
			// So now we just check if game over.

			let nextPhase = 'encounter';
			if (nextSession.wins >= 10) nextPhase = 'victory';
			if (nextSession.losses >= 4) nextPhase = 'game_over';

			nextSession.phase = nextPhase;
			nextSession.round += 1;
			nextSession.step = 1;
			nextSession.action_log = []; // Clear log for new round

			if (nextPhase === 'encounter') {
				const encounterResult = this.generateEncounterOptions(nextSession);
				nextSession.current_options = encounterResult.options;
			} else {
				nextSession.current_options = null;
			}

			nextSession.updated_at = new Date();
			return { session: nextSession };
		}

		return { session: nextSession };
	}

	// Normal Progression (Encounter/Shop)
	const newSeed = this.generateNextSeed(nextSession.seed, actionId);
	nextSession.seed = newSeed;

	// Log action
	const actionEntry = { round: nextSession.round, phase: nextSession.phase, step: nextSession.step, actionId, payload };
	nextSession.action_log = [...(nextSession.action_log || []), actionEntry];

	// Increment Step?
	// Logic from action/index.ts:
	// if (session.step < 7) ...

	let nextPhase = 'encounter';
	let nextOptions = null;
	let combatResult = undefined;

	if (nextSession.step % 2 !== 0) {
		// Odd -> Moving to Shop (2, 4, 6)
		if (actionId === 'upgrade_unit' || actionId === 'power_distributor' || actionId === 'power_absorber') {
			nextPhase = 'orb_shop';
			if (actionId === 'upgrade_unit') nextOptions = [{ id: 'upgrade_orb' }];
			if (actionId === 'power_distributor') nextOptions = [{ id: 'distribute_power_orb' }];
			if (actionId === 'power_absorber') nextOptions = [{ id: 'absorb_power_orb' }];
		} else {
			nextPhase = 'shop';
			// Generate Shop Options
			const shopResult = this.generateShopOptions(nextSession, actionId);
			nextOptions = shopResult.options;
		}
	} else {
		// Even -> Moving to Encounter (3, 5) or Combat (7)
		if (nextSession.step === 6) {
			nextPhase = 'combat';
		} else {
			nextPhase = 'encounter';
			const encounterResult = this.generateEncounterOptions(nextSession);
			nextOptions = encounterResult.options;
		}
	}

	nextSession.step += 1;
	nextSession.phase = nextPhase;
	nextSession.current_options = nextOptions ? { options: nextOptions } : null;

	// Special handling for entering COMBAT
	if (nextPhase === 'combat') {
		// Generate Enemy Team
		const enemyTeam = this.generateEnemyTeamForRound(nextSession.round, nextSession.wins);

		// Setup next session for simulation
		nextSession.current_options = { combatState: { enemyTeam } };

		// Run Simulation
		const simResult = this.simulateCombat(nextSession);
		const playerUnits = simResult.finalState.battleData.units.filter((u: any) => u.force === 'PLAYER');

		const outcomeLog = simResult.logs.find((l: any) => l.type === 'outcome');
		let wonCombat = false;
		if (outcomeLog) {
			wonCombat = outcomeLog.result === 'player_won';
		} else {
			const core = playerUnits.find((u: any) => u.isCore);
			wonCombat = !!(core && core.life > 0);
		}

		// Update Wins/Losses immediately? Use separate variables to track transition
		nextSession.wins += (wonCombat ? 1 : 0);
		nextSession.losses += (wonCombat ? 0 : 1);

		// Prepare Combat Result for Client
		const combatState = {
			enemyTeam,
			seed: newSeed,
			wonCombat,
			initialUnits: simResult.initialUnits,
			finalPlayerUnits: playerUnits,
			logs: simResult.logs
		};

		const options = [{ id: 'combat_done', label: 'Continue' }];
		nextSession.current_options = { options, combatState };

		combatResult = { won: wonCombat };
	}

	nextSession.updated_at = new Date();
	return { session: nextSession, combatResult };
}
}
