import { State } from "../Models/State";
import { Unit, makeUnit } from "../Models/Entities/Unit";
import { pickRandom } from "../utils";
import * as Card from "../Models/Entities/Card";
import * as BoardLogic from "../Models/BoardLogic";
import { generateEnemyTeam } from "../Scenes/Battleground/generateEnemyTeam";
import { runCombat } from "../Scenes/Battleground/RunCombatCore";
import { createServerCombatEffects } from "../Scenes/Battleground/ServerCombatEffects";
import { FORCE_ID_PLAYER, FORCE_ID_CPU } from "../Scenes/Battleground/ServerConstants";
import { makeForce } from "../Models/Entities/Force";
import { BASE_COLLECTION_DATA } from "../Data/BaseCollection";
import { registerCollection } from "../Models/Entities/Card";

// Register base collection to ensure unit definitions exist
registerCollection(BASE_COLLECTION_DATA);

const ENCOUNTER_IDS = [
	'upgrade_unit',
	'armory',
	'healing_tent',
	'frontier_fort',
	'forest_pools',
	'toxic_chamber',
	'trial_circuit',
	'trappers_guild',
	'thunder_spire',
	'commanders_tent',
	'assassins_hideout',
	'power_distributor',
	'power_absorber',
	'silver_shop',
	'gold_shop'
];

export interface SessionData {
	id: string;
	player_id: string;
	phase: string;
	round: number;
	step: number;
	seed: string;
	initial_seed: string;
	action_log: any[];
	current_options?: any[];
	wins: number;
	losses: number;
	team?: any;
	updated_at?: Date;
}

export class MultiplayerLogic {
	public static createInitialSession(playerId: string, selectedCrystalId?: string): SessionData {
		const seed = Math.random().toString(36).substring(7);
		const initialSeed = seed;

		let team: any = { units: [] };
		if (selectedCrystalId) {
			const coreUnit = makeUnit(FORCE_ID_PLAYER, selectedCrystalId, { x: 1, y: 1 });
			coreUnit.isCore = true;
			team.units.push(coreUnit);
		}

		const session: SessionData = {
			id: '', // Will be generated by DB
			player_id: playerId,
			phase: 'encounter',
			round: 1,
			step: 1,
			seed,
			initial_seed: initialSeed,
			action_log: [],
			wins: 0,
			losses: 0,
			team
		};

		const options = this.generateEncounterOptions(session);
		session.current_options = options.options;

		return session;
	}

	public static generateEnemyTeamForRound(round: number, wins: number): any[] {
		const allCards = Card.getAvailableCards();
		const mockState = {
			battleData: { forces: [makeForce(FORCE_ID_PLAYER), makeForce(FORCE_ID_CPU)] },
			gameData: { player: { wins } }
		} as any;
		return generateEnemyTeam(mockState, round, allCards);
	}

	public static stringToSeed(str: string): number {
		let hash = 0;
		for (let i = 0; i < str.length; i++) {
			const char = str.charCodeAt(i);
			hash = ((hash << 5) - hash) + char;
			hash = hash & hash;
		}
		return Math.abs(hash);
	}

	public static generateNextSeed(currentSeed: string, actionId: string): string {
		const input = currentSeed + actionId;
		let hash = 0;
		for (let i = 0; i < input.length; i++) {
			const char = input.charCodeAt(i);
			hash = ((hash << 5) - hash) + char;
			hash = hash & hash;
		}
		return Math.abs(hash).toString(36);
	}

	public static generateEncounterOptions(session: SessionData): { options: any[], nextPhase?: string } {
		if (session.step === 7) {
			return { options: [{ id: 'combat_encounter' }] };
		}

		const seedNum = this.stringToSeed(session.seed);
		const shuffled = [...ENCOUNTER_IDS];
		let currentSeedVal = seedNum;

		for (let i = shuffled.length - 1; i > 0; i--) {
			const x = Math.sin(currentSeedVal++) * 10000;
			const rnd = x - Math.floor(x);
			const j = Math.floor(rnd * (i + 1));
			[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
		}

		return { options: shuffled.slice(0, 3).map(id => ({ id })) };
	}

	public static generateShopOptions(session: SessionData): { options: any[] } {
		const previousStep = session.step - 1;
		const lastEncounterAction = session.action_log.find((a: any) => a.round === session.round && a.step === previousStep);
		const encounterId = lastEncounterAction ? lastEncounterAction.actionId : null;

		let filterType = "";
		if (encounterId) {
			if (encounterId === 'armory') filterType = 'damage';
			else if (encounterId === 'healing_tent') filterType = 'heal';
			else if (encounterId === 'frontier_fort') filterType = 'shield';
			else if (encounterId === 'forest_pools') filterType = 'regen';
			else if (encounterId === 'toxic_chamber') filterType = 'poison';
			else if (encounterId === 'trial_circuit') filterType = 'haste';
			else if (encounterId === 'trappers_guild') filterType = 'slow';
			else if (encounterId === 'thunder_spire') filterType = 'charge';
			else if (encounterId === 'commanders_tent') filterType = 'increase_power';
			else if (encounterId === 'assassins_hideout') filterType = 'increase_critical';
			else if (encounterId === 'silver_shop') filterType = 'silver';
			else if (encounterId === 'gold_shop') filterType = 'gold';
		}

		const allCards = Card.getAvailableCards();
		let filteredCards = allCards;

		if (filterType) {
			if (filterType === 'silver') {
				filteredCards = allCards.filter(card => card.rank === 2);
			} else if (filterType === 'gold') {
				filteredCards = allCards.filter(card => card.rank === 3);
			} else {
				filteredCards = allCards.filter(card =>
				(card.effects?.some(eff => eff.id === filterType) ||
					card.reactions?.some(react => react.effects?.some(eff => eff.id === filterType)))
				);
			}
		}

		if (filteredCards.length === 0) {
			filteredCards = allCards;
		}

		const options = pickRandom(filteredCards, 3).map(card => ({
			id: card.id,
			cost: 10
		}));

		return { options };
	}

	public static resolveAction(session: SessionData, actionId: string, payload?: any): { team: any, updates?: string[] } {
		// Returns modified team object
		const availableCards = Card.getAvailableCards();
		const card = availableCards.find(c => c.id === actionId);

		let team = session.team ? JSON.parse(JSON.stringify(session.team)) : { units: [] };
		let units = team.units || [];
		const updates: string[] = [];

		if (card) {
			const existingUnitIndex = units.findIndex((u: any) => u.cardId === actionId);
			if (existingUnitIndex >= 0) {
				const existingUnit = units[existingUnitIndex];
				if (existingUnit.rank < 4) {
					existingUnit.rank++;
					existingUnit.maxLife = Math.floor(existingUnit.maxLife * 1.5);
					existingUnit.life = existingUnit.maxLife;
					existingUnit.power = Math.floor(existingUnit.power * 1.5);
					updates.push(`Upgraded unit ${actionId} to rank ${existingUnit.rank}`);
				}
			} else {
				if (units.length < 9) {
					const targetPos = BoardLogic.getEmptySlot(units, FORCE_ID_PLAYER);
					if (targetPos) {
						const newUnit = makeUnit(FORCE_ID_PLAYER, actionId, targetPos);

						// Silver/Gold Shop Context Logic
						const previousStep = session.step - 1;
						const lastEncounterAction = session.action_log.find((a: any) => a.round === session.round && a.step === previousStep);
						const encounterId = lastEncounterAction ? lastEncounterAction.actionId : null;
						let targetRank = 1;
						if (encounterId === 'silver_shop') targetRank = 2;
						if (encounterId === 'gold_shop') targetRank = 3;

						if (targetRank > 1) {
							newUnit.rank = targetRank;
							const extraLevels = targetRank - 1;
							for (let i = 0; i < extraLevels; i++) {
								newUnit.maxLife = Math.floor(newUnit.maxLife * 1.5);
								newUnit.life = newUnit.maxLife;
								newUnit.power = Math.floor(newUnit.power * 1.5);
							}
							updates.push(`Recruited unit ${actionId} at Rank ${newUnit.rank}`);
						}

						units.push(newUnit);
						updates.push(`Added new unit ${actionId}`);
					}
				}
			}
		} else {
			// Orb/Encounter Logic
			if (actionId === 'apply_orb' && payload) {
				const { orbId, targetUnitId } = payload;
				const targetUnit = units.find((u: any) => u.id === targetUnitId);
				if (targetUnit) {
					updates.push(`Applying orb ${orbId} to ${targetUnitId}`);
					if (payload.orbId === 'upgrade_orb') {
						targetUnit.rank = (targetUnit.rank || 1) + 1;
						targetUnit.maxLife = Math.floor(targetUnit.maxLife * 1.5);
						targetUnit.life = targetUnit.maxLife;
						targetUnit.power = Math.floor(targetUnit.power * 1.5);
					} else if (payload.orbId === 'absorb_power_orb') {
						let totalAbsorbed = 0;
						units.forEach((u: any) => {
							if (u.id !== targetUnit.id && u.position && u.position.y === targetUnit.position.y) {
								const absorbed = Math.floor(u.power * 0.25);
								if (absorbed > 0) {
									u.power = Math.max(0, u.power - absorbed);
									totalAbsorbed += absorbed;
								}
							}
						});
						if (totalAbsorbed > 0) {
							targetUnit.power = (targetUnit.power || 0) + totalAbsorbed;
							targetUnit.bonusPower = (targetUnit.bonusPower || 0) + totalAbsorbed;
						}
					} else if (payload.orbId === 'distribute_power_orb') {
						const powerToDistribute = Math.floor(targetUnit.power * 0.5);
						if (powerToDistribute > 0) {
							targetUnit.power = Math.max(0, targetUnit.power - powerToDistribute);
							const bonusToLose = Math.max(0, Math.min(targetUnit.bonusPower || 0, powerToDistribute));
							targetUnit.bonusPower = (targetUnit.bonusPower || 0) - bonusToLose;

							const targets = units.filter((u: any) => u.id !== targetUnit.id && u.position && u.position.y === targetUnit.position.y);
							if (targets.length > 0) {
								const powerPerTarget = Math.floor(powerToDistribute / targets.length);
								targets.forEach((u: any) => {
									u.power = (u.power || 0) + powerPerTarget;
									u.bonusPower = (u.bonusPower || 0) + powerPerTarget;
								});
							}
						}
					}
				}
			}
		}

		team.units = units;
		return { team, updates };
	}

	public static simulateCombat(session: SessionData): { finalState: State, initialUnits: Unit[], logs: any[] } {
		const combatState = this.createCombatState(session);
		const initialUnits = JSON.parse(JSON.stringify(combatState.battleData.units));

		const effects = createServerCombatEffects(combatState);
		const combatRunner = runCombat(combatState, effects);

		const SIM_DELTA = 16.67;
		let frame = 0;
		const MAX_FRAMES = 10000;
		while (combatRunner.isActive() && frame < MAX_FRAMES) {
			effects.setFrame(frame);
			combatRunner.updateFrame(combatState, frame * SIM_DELTA, SIM_DELTA);
			frame++;
		}

		return { finalState: combatState, initialUnits, logs: effects.logs };
	}

	private static createCombatState(session: SessionData): State {
		let playerUnits: Unit[] = [];
		if (session.team && (session.team as any).units) {
			playerUnits = JSON.parse(JSON.stringify((session.team as any).units));
			playerUnits.forEach(u => {
				u.effects = u.effects || [];
				u.reactions = u.reactions || [];
				u.life = u.maxLife;
			});
		}

		const hasCore = playerUnits.some(u => u.isCore);
		if (!hasCore) {
			const freeSlot = BoardLogic.findFreeSlot(playerUnits, FORCE_ID_PLAYER, { x: 1, y: 1 });
			if (freeSlot) {
				const crystal = makeUnit(FORCE_ID_PLAYER, "crystal_core", freeSlot);
				crystal.isCore = true;
				playerUnits.push(crystal);
			}
		}

		let enemyUnits: Unit[] = [];
		if (session.current_options && (session.current_options as any).combatState && (session.current_options as any).combatState.enemyTeam) {
			enemyUnits = JSON.parse(JSON.stringify((session.current_options as any).combatState.enemyTeam));
		} else {
			const allCards = Card.getAvailableCards();
			const mockState = {
				battleData: { forces: [makeForce(FORCE_ID_PLAYER), makeForce(FORCE_ID_CPU)] },
				gameData: { player: { wins: session.wins || 0 } }
			} as any;
			enemyUnits = generateEnemyTeam(mockState, session.round, allCards);
		}

		return {
			savedGames: [],
			gameData: {
				round: session.round,
				hour: 0,
				player: makeForce(FORCE_ID_PLAYER),
				recentEncounterIds: [],
				runStats: {} as any,
				seed: this.stringToSeed(session.initial_seed),
				initialSeed: this.stringToSeed(session.initial_seed),
				isSeeded: true
			},
			battleData: {
				forces: [makeForce(FORCE_ID_PLAYER), makeForce(FORCE_ID_CPU)],
				grid: BoardLogic.createGrid(),
				units: [...playerUnits, ...enemyUnits]
			}
		};
	}
}
