create table if not exists public.ghosts (
	id bigint generated by default as identity primary key,
	player_id text,
	round integer,
	session_type text,
	team jsonb,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'ghosts'
			and column_name = 'team_composition'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'ghosts'
			and column_name = 'team'
	) then
		alter table public.ghosts rename column team_composition to team;
	end if;
end
$$;

alter table public.ghosts
	add column if not exists player_id text,
	add column if not exists round integer,
	add column if not exists session_type text,
	add column if not exists team jsonb,
	add column if not exists created_at timestamptz not null default now(),
	add column if not exists updated_at timestamptz not null default now();

alter table public.ghosts
	alter column created_at set default now(),
	alter column updated_at set default now();

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'ghosts'
			and column_name = 'team_composition'
	) then
		execute 'update public.ghosts set team = coalesce(team, team_composition)';
		execute 'alter table public.ghosts alter column team_composition drop not null';
	end if;
end
$$;

update public.ghosts
set
	session_type = coalesce(session_type, 'multiplayer_casual'),
	created_at = coalesce(created_at, now()),
	updated_at = coalesce(updated_at, now())
where session_type is null
	or created_at is null
	or updated_at is null;

delete from public.ghosts
where player_id is null
	or round is null
	or team is null;

with duplicate_ghosts as (
	select ctid
	from (
		select
			ctid,
			row_number() over (
				partition by player_id, round, session_type
				order by updated_at desc nulls last, created_at desc nulls last, id desc nulls last
			) as row_num
		from public.ghosts
	) ranked
	where ranked.row_num > 1
)
delete from public.ghosts ghosts
using duplicate_ghosts
where ghosts.ctid = duplicate_ghosts.ctid;

alter table public.ghosts
	alter column player_id set not null,
	alter column round set not null,
	alter column session_type set not null,
	alter column team set not null;

create unique index if not exists ghosts_player_round_queue_idx
	on public.ghosts (player_id, round, session_type);

create index if not exists ghosts_round_queue_lookup_idx
	on public.ghosts (round, session_type, updated_at desc);

do $$
begin
	if not exists (
		select 1
		from pg_constraint
		where conname = 'ghosts_round_positive'
			and conrelid = 'public.ghosts'::regclass
	) then
		alter table public.ghosts
			add constraint ghosts_round_positive
			check (round > 0);
	end if;

	if not exists (
		select 1
		from pg_constraint
		where conname = 'ghosts_session_type_valid'
			and conrelid = 'public.ghosts'::regclass
	) then
		alter table public.ghosts
			add constraint ghosts_session_type_valid
			check (session_type in ('multiplayer_ranked', 'multiplayer_casual'));
	end if;

	if not exists (
		select 1
		from pg_constraint
		where conname = 'ghosts_team_object'
			and conrelid = 'public.ghosts'::regclass
	) then
		alter table public.ghosts
			add constraint ghosts_team_object
			check (jsonb_typeof(team) = 'object');
	end if;
end
$$;

alter table public.ghosts enable row level security;
