import { SCREEN_WIDTH, TILE_WIDTH } from "../../../../constants/constants";

export const NUM_TAVERN_SLOTS = 3;
const PANEL_PADDING = 40;
const TAVERN_PADDING = 20;
export const TAVERN_CHARA_SPACING = 300;
const BUTTON_AREA_HEIGHT = 100;

const TAVERN_CHARAS_TOTAL_WIDTH = (NUM_TAVERN_SLOTS - 1) * TAVERN_CHARA_SPACING + TILE_WIDTH;

export const TAVERN_BG_WIDTH = TAVERN_CHARAS_TOTAL_WIDTH + (TAVERN_PADDING * 2);
export const TAVERN_BG_HEIGHT = 400;

export const SHOP_PANEL_WIDTH = TAVERN_BG_WIDTH + (PANEL_PADDING * 2);
export const SHOP_PANEL_HEIGHT = TAVERN_BG_HEIGHT + BUTTON_AREA_HEIGHT + (PANEL_PADDING * 2) + 100;

export const PANEL_X = (SCREEN_WIDTH - SHOP_PANEL_WIDTH) / 2;
export const PANEL_Y = 240;

export const TAVERN_BASE_X = PANEL_X + PANEL_PADDING;
export const TAVERN_BASE_Y = PANEL_Y + PANEL_PADDING;

export const TAVERN_TITLE_X = TAVERN_BASE_X + TAVERN_PADDING;
export const TAVERN_TITLE_Y = TAVERN_BASE_Y + 15;

export const TAVERN_CHARA_FIRST_X = TAVERN_BASE_X + (600);
export const TAVERN_CHARA_BASE_Y = TAVERN_BASE_Y + 180;

export const PANEL_BG_COLOR = 0x2c3e50;
export const PANEL_BG_OPACITY = 0.95;
export const SUB_PANEL_CORNER_RADIUS = 15;

export const SELL_ZONE_WIDTH = SHOP_PANEL_WIDTH;
export const SELL_ZONE_HEIGHT = SHOP_PANEL_HEIGHT;
export const SELL_ZONE_Y_OFFSET_FROM_BOTTOM = 0;
export const SELL_ZONE_BG_COLOR = 0xffa500;
export const SELL_ZONE_BG_ALPHA = 0.7;
export const SELL_ZONE_TEXT = "SELL";
export const SELL_ZONE_TEXT_STYLE = { fontSize: '32px', color: '#000000', fontStyle: 'bold' };
export const SELL_ZONE_CORNER_RADIUS = 10;
export const SHOP_SELL_ZONE_NAME = "shop_sell_zone";

export const SHOP_ITEM_APPEAR_SCALE_DURATION = 400;
export const SHOP_ITEM_APPEAR_WIGGLE_ANGLE = 10;
export const SHOP_ITEM_APPEAR_WIGGLE_DURATION_1 = 100;
export const SHOP_ITEM_APPEAR_WIGGLE_DURATION_2 = 100;
export const SHOP_ITEM_APPEAR_WIGGLE_RETURN_DURATION = 50;