#!/bin/bash

# Encode a locally-cached Steam session (config.vdf) into the base64 form the
# publish script / CI uses (STEAM_CONFIG_VDF_B64) so `make steam-publish` runs
# fully unattended — no password or MFA prompts.
#
# Usage:
#   steam/scripts/encode_config_vdf.sh               # print the base64 (for CI secrets)
#   steam/scripts/encode_config_vdf.sh --update-env  # also write it into the root .env
#
# The session MUST be generated by steamcmd — the Steam desktop client's own
# config.vdf does NOT contain the cached-credential block steamcmd needs (it
# has no "accounts" section). Create it once on this machine:
#   steamcmd +login <user> +quit     # type the password + emailed code when asked
# (close the Steam desktop client first — both write the same config.vdf file)
#
# Caveats:
#   - The config.vdf belongs to the account that logged in via steamcmd. If the
#     session expires (steamcmd says "License expired"), re-login + re-encode.
#   - It is an auth token — the encoded value is secret. Keep it in the
#     gitignored .env or a secrets manager only.

set -euo pipefail

REPO_ROOT=$(cd "$(dirname "$0")/../.." && pwd)
ENV_FILE="$REPO_ROOT/.env"

CONFIG=""
case "$(uname -s)" in
    Darwin)
        CONFIG="$HOME/Library/Application Support/Steam/config/config.vdf"
        ;;
    Linux)
        for c in \
            "$HOME/.local/share/Steam/config/config.vdf" \
            "$HOME/Steam/config/config.vdf" \
            "$HOME/.steam/root/config/config.vdf"; do
            [ -f "$c" ] && { CONFIG="$c"; break; }
        done
        ;;
    *)
        echo "Error: unsupported OS ($(uname -s))." >&2
        exit 1
        ;;
esac

if [ -z "$CONFIG" ] || [ ! -s "$CONFIG" ]; then
    echo "No cached Steam session found (looked for: $CONFIG)." >&2
    echo "" >&2
    echo "Log in once with steamcmd first:" >&2
    echo "  steamcmd +login <user> +quit" >&2
    echo "and complete the emailed Steam Guard code when asked." >&2
    exit 1
fi

# steamcmd needs the "Accounts" (cached-credential) block; the Steam desktop
# client's config.vdf doesn't have it and can't be reused by steamcmd.
if ! grep -q '"Accounts"' "$CONFIG"; then
    echo "Error: $CONFIG has no \"Accounts\" section — no cached Steam credentials." >&2
    echo "" >&2
    echo "The Steam desktop client's session can't be reused by steamcmd. Generate" >&2
    echo "the session with steamcmd itself (close the Steam client first):" >&2
    echo "  steamcmd +login <user> +quit" >&2
    echo "then type the password and the emailed Steam Guard code when asked." >&2
    exit 1
fi

# Single-line base64 (base64 wraps at 76 chars; .env needs one line).
B64=$(base64 < "$CONFIG" | tr -d '\n')

if [ "${1:-}" = "--update-env" ]; then
    if [ -f "$ENV_FILE" ] && grep -qE '^STEAM_CONFIG_VDF_B64=' "$ENV_FILE"; then
        sed -i.bak "s|^STEAM_CONFIG_VDF_B64=.*|STEAM_CONFIG_VDF_B64=$B64|" "$ENV_FILE"
        rm -f "$ENV_FILE.bak"
    else
        printf '\n# Steam cached session (steam/scripts/encode_config_vdf.sh) — auth token, keep secret.\nSTEAM_CONFIG_VDF_B64=%s\n' "$B64" >> "$ENV_FILE"
    fi
    echo "Updated $ENV_FILE with STEAM_CONFIG_VDF_B64 (encoded from $CONFIG)."
    echo "Now run: make steam-publish    (or: make steam-publish-demo)"
else
    echo "$B64"
    echo ""
    echo "Copy the line above into .env as STEAM_CONFIG_VDF_B64=..., or re-run with --update-env." >&2
fi
