import { BasePhaseHandler } from "../BasePhaseHandler";
import { PhaseTransitionContext, PhaseTransitionResult, ActionType } from "../types";
import { GameLogic } from "../../GameLogic";
import { PhaseType } from "../../Types";

export class EncounterPhaseHandler extends BasePhaseHandler {
	readonly phase: PhaseType = 'encounter';
	readonly actionType = ActionType.PHASE_TRANSITION;

	protected computeTransition(context: PhaseTransitionContext): PhaseTransitionResult {
		const { session, actionId } = context;

		// Handle combat warning
		if (actionId === 'combat_encounter') {
			return {
				nextPhase: 'combat',
				nextOptions: [], // Combat options usually generated by combat setup or empty initially? 
				// GameLogic sets combatState but options are empty/null until combat starts?
				// Actually GameLogic.transitionToNextState calls generateEnemyTeamForRound...
				// and sets options to null? No, wait.
				// It says: nextSession.current_options = { combatState: { enemyTeam } };
				// So options array is likely undefined or empty.
				specialData: {
					// We'll let the system fill this via a "CombatSetup" or similar, 
					// BUT GameLogic does it here.
					// Ideally we delegate this. For now let's reuse GameLogic logic via a service or similar?
					// The handler needs to return the *data* required for the next state.
					startCombat: true // Signal to generating system
				}
			};
		}

		// Handle special encounters -> Orb Shop
		const specialOrbEncounters = ['upgrade_unit', 'power_distributor', 'power_absorber'];
		if (specialOrbEncounters.includes(actionId)) {
			let nextOptions: any[] = [];
			if (actionId === 'upgrade_unit') nextOptions = [{ id: 'upgrade_orb' }];
			if (actionId === 'power_distributor') nextOptions = [{ id: 'distribute_power_orb' }];
			if (actionId === 'power_absorber') nextOptions = [{ id: 'absorb_power_orb' }];

			return {
				nextPhase: 'orb_shop',
				nextOptions,
				stepIncrement: 1
			};
		}

		// Handle skip encounter -> Shop
		if (actionId === 'skip_encounter') {
			const shopResult = GameLogic.generateShopOptions(session);
			return {
				nextPhase: 'shop',
				nextOptions: shopResult.options,
				stepIncrement: 1
			};
		}

		// Default: Selected an encounter -> Shop
		// The actionId IS the encounter ID
		const shopResult = GameLogic.generateShopOptions(session, actionId);
		return {
			nextPhase: 'shop',
			nextOptions: shopResult.options,
			stepIncrement: 1
		};
	}
}
