import * as esbuild from "esbuild";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectRoot = path.resolve(__dirname, "..");
const srcDir = path.join(projectRoot, "src");
const functionsDir = path.join(projectRoot, "supabase/functions");

const rewriteMap: Record<string, string> = {
	"@supabase/supabase-js": "https://esm.sh/@supabase/supabase-js@2",
};

function rewriteAndValidateImports(outFile: string): void {
	let content = fs.readFileSync(outFile, "utf8");

	for (const [pkg, url] of Object.entries(rewriteMap)) {
		const pattern = new RegExp(`from\\s+[\"']${pkg}[\"']`, "g");
		content = content.replace(pattern, `from \"${url}\"`);
	}

	const bareImportPattern =
		/(?:^|\n)\s*import\s+(?:[^"'\n]+\s+from\s+)?["'](?!\.{1,2}\/|https?:\/\/|data:|node:)([^"']+)["']/g;
	const unresolved = new Set<string>();
	let match: RegExpExecArray | null;
	while ((match = bareImportPattern.exec(content)) !== null) {
		unresolved.add(match[1]);
	}

	if (unresolved.size > 0) {
		throw new Error(
			`Found unsupported bare imports in ${path.basename(outFile)}: ${Array.from(unresolved).join(", ")}`
		);
	}

	fs.writeFileSync(outFile, content, "utf8");
}

async function bundle(functionName: string, entryPoint: string) {
	const outDir = path.join(functionsDir, functionName);
	const outFile = path.join(outDir, "_shared.js");

	console.log(`Bundling ${entryPoint} to ${outFile}...`);

	if (!fs.existsSync(outDir)) {
		fs.mkdirSync(outDir, { recursive: true });
	}

	try {
		await esbuild.build({
			entryPoints: [entryPoint],
			bundle: true,
			outfile: outFile,
			format: "esm",
			platform: "neutral", // Agnostic platform (Deno-compatible ESM)
			target: "esnext",
			external: ["pg", "express", "@supabase/supabase-js"], // Externalize Node/Client libs. Phaser bundled (Mocked).
			alias: {
				// Mock Phaser for Deno environment
				phaser: path.join(srcDir, "MockPhaser.ts"),
				// Stub out the browser entry-point so AudioManager (and anything else
				// that does `import { game } from "@main"`) doesn't pull in the full
				// Phaser scene graph (CrystalSelectionScene, rex-plugins, etc.).
				"@main": path.join(srcDir, "stubs/MockMain.ts"),
			},
			define: {
				"process.env.NODE_ENV": '"production"',
				global: "globalThis", // Deno compat
			},
			banner: {
				js: `// Auto-generated by scripts/bundle-edge.ts. DO NOT EDIT.
if (typeof globalThis.window === "undefined") globalThis.window = globalThis;
if (typeof globalThis.localStorage === "undefined") {
	const store = new Map();
	globalThis.localStorage = {
		get length() { return store.size; },
		clear() { store.clear(); },
		getItem(key) { return store.has(key) ? store.get(key) : null; },
		key(index) { return Array.from(store.keys())[index] ?? null; },
		removeItem(key) { store.delete(key); },
		setItem(key, value) { store.set(String(key), String(value)); },
	};
}
if (typeof globalThis.Phaser === "undefined") {
	globalThis.Phaser = {
		Scene: class Scene {},
		Scenes: { Events: { SHUTDOWN: "shutdown" } },
		Plugins: { BasePlugin: class BasePlugin {}, PluginCache: { register() {} } },
		GameObjects: { Graphics: class Graphics {}, GameObject: class GameObject {}, Components: {}, Events: {}, BuildGameObject() {}, Mesh: class Mesh {} },
		Display: { BaseShader: class BaseShader {}, Canvas: { CanvasPool: { create() { return {}; }, remove() {} } } },
		BlendModes: { ADD: "ADD", NORMAL: "NORMAL" },
		Geom: { Circle: class Circle {}, Rectangle: class Rectangle {}, Triangle: class Triangle {}, Mesh: class Mesh {} },
		Cameras: { Scene2D: { Camera: class Camera {} } },
		Input: { Keyboard: { KeyCodes: {} }, Events: {} },
		Curves: { Path: class Path { lineTo() { return this; } } },
		Renderer: { WebGL: { Utils: {} } },
		Utils: { Objects: { GetValue() {}, GetAdvancedValue() {}, GetFastValue() {}, IsPlainObject() { return false; } }, String: { Pad(s) { return String(s); }, UUID() { return ""; } } },
		Scale: { FIT: 3, CENTER_BOTH: 1, NO_CENTER: 0 },
		DOM: { AddToDOM() {}, RemoveFromDOM() {} },
		Textures: { DynamicTexture: class DynamicTexture {} },
		VERSION: "3.60.0",
		Class: { mixin() {} },
		Math: globalThis.Math,
	};
}
`,
			},
		});

		rewriteAndValidateImports(outFile);
		console.log(`✅ Success: ${outFile}`);
	} catch (e) {
		console.error(`❌ Failed to bundle ${functionName}:`, e);
		process.exit(1);
	}
}

// Bundle Logic for 'action' function
bundle("action", path.join(srcDir, "Core/GameLogic.ts"));

// Bundle Logic for 'replay-commit' function (same shared logic — replay uses the same GameLogic)
bundle("replay-commit", path.join(srcDir, "Core/GameLogic.ts"));

// Bundle Logic for 'get-enemy-team' function (needs generateEnemyTeamForRound from GameLogic)
bundle("get-enemy-team", path.join(srcDir, "Core/GameLogic.ts"));
