import * as esbuild from "esbuild";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectRoot = path.resolve(__dirname, "..");
const srcDir = path.join(projectRoot, "src");
const functionsDir = path.join(projectRoot, "supabase/functions");

async function bundle(functionName: string, entryPoint: string) {
	const outDir = path.join(functionsDir, functionName);
	const outFile = path.join(outDir, "_shared.js");

	console.log(`Bundling ${entryPoint} to ${outFile}...`);

	if (!fs.existsSync(outDir)) {
		fs.mkdirSync(outDir, { recursive: true });
	}

	try {
		await esbuild.build({
			entryPoints: [entryPoint],
			bundle: true,
			outfile: outFile,
			format: "esm",
			platform: "neutral", // Agnostic platform (Deno-compatible ESM)
			target: "esnext",
			external: ["pg", "express", "@supabase/supabase-js"], // Externalize Node/Client libs. Phaser bundled (Mocked).
			alias: {
				// Mock Phaser for Deno environment
				phaser: path.join(srcDir, "MockPhaser.ts"),
			},
			define: {
				"process.env.NODE_ENV": '"production"',
				global: "globalThis", // Deno compat
			},
			banner: {
				js: "// Auto-generated by scripts/bundle-edge.ts. DO NOT EDIT.",
			},
		});
		console.log(`✅ Success: ${outFile}`);
	} catch (e) {
		console.error(`❌ Failed to bundle ${functionName}:`, e);
		process.exit(1);
	}
}

// Bundle Logic for 'action' function
bundle("action", path.join(srcDir, "Multiplayer/MultiplayerLogic.ts"));

// Bundle Logic for 'replay-commit' function (same shared logic — replay uses the same GameLogic)
bundle("replay-commit", path.join(srcDir, "Multiplayer/MultiplayerLogic.ts"));
