import * as esbuild from "esbuild";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectRoot = path.resolve(__dirname, "..");
const srcDir = path.join(projectRoot, "src");
const functionsDir = path.join(projectRoot, "supabase/functions");

const rewriteMap: Record<string, string> = {
	"@supabase/supabase-js": "https://esm.sh/@supabase/supabase-js@2",
};

function rewriteAndValidateImports(outFile: string): void {
	let content = fs.readFileSync(outFile, "utf8");

	for (const [pkg, url] of Object.entries(rewriteMap)) {
		const pattern = new RegExp(`from\\s+[\"']${pkg}[\"']`, "g");
		content = content.replace(pattern, `from \"${url}\"`);
	}

	const bareImportPattern =
		/(?:^|\n)\s*import\s+(?:[^"'\n]+\s+from\s+)?["'](?!\.{1,2}\/|https?:\/\/|data:|node:)([^"']+)["']/g;
	const unresolved = new Set<string>();
	let match: RegExpExecArray | null;
	while ((match = bareImportPattern.exec(content)) !== null) {
		unresolved.add(match[1]);
	}

	if (unresolved.size > 0) {
		throw new Error(
			`Found unsupported bare imports in ${path.basename(outFile)}: ${Array.from(unresolved).join(", ")}`
		);
	}

	fs.writeFileSync(outFile, content, "utf8");
}

async function bundle(functionName: string, entryPoint: string) {
	const outDir = path.join(functionsDir, functionName);
	const outFile = path.join(outDir, "_shared.js");

	console.log(`Bundling ${entryPoint} to ${outFile}...`);

	if (!fs.existsSync(outDir)) {
		fs.mkdirSync(outDir, { recursive: true });
	}

	try {
		await esbuild.build({
			entryPoints: [entryPoint],
			bundle: true,
			outfile: outFile,
			format: "esm",
			platform: "neutral", // Agnostic platform (Deno-compatible ESM)
			target: "esnext",
			external: ["pg", "express", "@supabase/supabase-js"], // Externalize Node/Client libs. Phaser bundled (Mocked).
			alias: {
				// Mock Phaser for Deno environment
				phaser: path.join(srcDir, "MockPhaser.ts"),
			},
			define: {
				"process.env.NODE_ENV": '"production"',
				global: "globalThis", // Deno compat
			},
			banner: {
				js: "// Auto-generated by scripts/bundle-edge.ts. DO NOT EDIT.",
			},
		});

		rewriteAndValidateImports(outFile);
		console.log(`✅ Success: ${outFile}`);
	} catch (e) {
		console.error(`❌ Failed to bundle ${functionName}:`, e);
		process.exit(1);
	}
}

// Bundle Logic for 'action' function
bundle("action", path.join(srcDir, "Core/GameLogic.ts"));

// Bundle Logic for 'replay-commit' function (same shared logic — replay uses the same GameLogic)
bundle("replay-commit", path.join(srcDir, "Core/GameLogic.ts"));
