/**
 * new-screen — scaffold a new screen module following the canonical
 * @mana/framework pattern (see docs/framework-formalization.md Phase D).
 *
 * Usage:
 *   npm run new:screen -- <Name>
 *
 * Example:
 *   npm run new:screen -- Inventory
 *   → creates phaser/src/Screens/Inventory/InventoryScreen.ts
 *
 * The script only creates the screen file.  Wiring it up is a manual,
 * deliberate step (printed as a checklist after generation).
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const screensRoot = path.resolve(here, "../src/Screens");

const rawName = process.argv[2];

if (!rawName) {
	console.error("Usage: npm run new:screen -- <Name>");
	console.error("Example: npm run new:screen -- Inventory");
	process.exit(1);
}

// Normalise to PascalCase ("inventory" | "Inventory" | "inventory-screen" → "Inventory")
const pascal = rawName
	.split(/[-_\s]+/)
	.filter(Boolean)
	.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
	.join("")
	.replace(/Screen$/, "");

if (!/^[A-Z][A-Za-z0-9]*$/.test(pascal)) {
	console.error(`Invalid screen name: "${rawName}" — use letters/digits, e.g. "Inventory".`);
	process.exit(1);
}

const routeName = pascal.charAt(0).toLowerCase() + pascal.slice(1);
const dir = path.join(screensRoot, pascal);
const file = path.join(dir, `${pascal}Screen.ts`);

if (fs.existsSync(file)) {
	console.error(`Screen already exists: ${path.relative(process.cwd(), file)}`);
	process.exit(1);
}

const template = `/**
 * ${pascal}Screen — generated by \`npm run new:screen\`.
 *
 * Canonical screen pattern (@mana/framework):
 *   - events() wires screen-local events + listeners per entry; both are
 *     disposed automatically on destroy.
 *   - create() builds the persistent layer (survives phase switches);
 *     return Destroyable(s) or use ctx.track(obj, { id }) to auto-clean.
 *   - phases declare mutually exclusive sub-states; tracked elements are
 *     auto-destroyed on transition.  For a single-view screen, remove the
 *     phases block and use createScreen<never, ${pascal}Events>.
 */
import { createEvent } from "@game/Models";
import { createScreen, screenModule } from "@mana/framework";
import { getScreenManager } from "../ScreenManager";

export type ${pascal}Events = {
	backClicked: ReturnType<typeof createEvent<void>>;
};

export type ${pascal}Phase = "main";

const screen = createScreen<${pascal}Phase, ${pascal}Events>({
	name: "${routeName}",

	events: () => {
		const backClicked = createEvent<void>();

		return {
			events: { backClicked },
			listeners: [
				backClicked.listen(() => {
					void getScreenManager().go("title");
				}),
			],
		};
	},

	create: async (ctx) => {
		// TODO: build persistent UI here (survives phase switches).
		await ctx.go("main");
	},

	phases: {
		main: (_ctx) => {
			// TODO: build phase UI here (auto-destroyed on the next transition).
			// Return Destroyable(s) or use _ctx.track() to register cleanup.
		},
	},
});

export const { init, create, destroy, go, name } = screenModule(screen);
`;

fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(file, template);

console.log(`Created ${path.relative(process.cwd(), file)}`);
console.log("");
console.log("Next steps:");
console.log(`  1. Add the route to Routes in src/Screens/ScreenManager.ts:`);
console.log(`       ${routeName}: void;`);
console.log(`  2. Register the screen in Client.ts:`);
console.log(`       import * as ${pascal}Screen from "./Screens/${pascal}/${pascal}Screen";`);
console.log(`       // screens: { ..., ${routeName}: ${pascal}Screen }`);
console.log(`  3. Navigate with getScreenManager().go("${routeName}")`);
