/**
 * new-screen — scaffold a new screen scene following the raw-Phaser pattern
 * (see src/Scenes/ScreenScene.ts and docs/scene-migration.md).
 *
 * Usage:
 *   npm run new:screen -- <Name>
 *
 * Example:
 *   npm run new:screen -- Inventory
 *   → creates phaser/src/Screens/Inventory/InventoryScene.ts
 *
 * The script only creates the scene file.  Wiring it up is a manual,
 * deliberate step (printed as a checklist after generation).
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const screensRoot = path.resolve(here, "../src/Screens");

const rawName = process.argv[2];

if (!rawName) {
	console.error("Usage: npm run new:screen -- <Name>");
	console.error("Example: npm run new:screen -- Inventory");
	process.exit(1);
}

// Normalise to PascalCase ("inventory" | "Inventory" | "inventory-screen" → "Inventory")
const pascal = rawName
	.split(/[-_\s]+/)
	.filter(Boolean)
	.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
	.join("")
	.replace(/Scene$/, "")
	.replace(/Screen$/, "");

if (!/^[A-Z][A-Za-z0-9]*$/.test(pascal)) {
	console.error(`Invalid screen name: "${rawName}" — use letters/digits, e.g. "Inventory".`);
	process.exit(1);
}

const routeName = pascal.charAt(0).toLowerCase() + pascal.slice(1);
const dir = path.join(screensRoot, pascal);
const file = path.join(dir, `${pascal}Scene.ts`);

if (fs.existsSync(file)) {
	console.error(`Screen already exists: ${path.relative(process.cwd(), file)}`);
	process.exit(1);
}

const template = `/**
 * ${pascal}Scene — generated by \`npm run new:screen\`.
 *
 * Raw Phaser screen (see src/Scenes/ScreenScene.ts):
 *   - one Phaser scene per screen; on exit Phaser destroys its game objects,
 *     tweens, timers and scene listeners automatically
 *   - build the UI in buildScreen()
 *   - reset module-level state (flags, DOM nodes, @game event subscriptions)
 *     in onScreenShutdown() — Phaser cannot know about those
 *   - navigate with go("route") from @Scenes/AppRouter
 */
import { go } from "@Scenes/AppRouter";
import { ScreenScene } from "@Scenes/ScreenScene";

export const ${pascal.toUpperCase()}_SCENE_KEY = "${routeName}";

export class ${pascal}Scene extends ScreenScene {
	constructor() {
		super({ key: ${pascal.toUpperCase()}_SCENE_KEY });
	}

	protected buildScreen(): void {
		// TODO: build the screen (env.scene.add.* / shared components).
	}

	protected onScreenShutdown(): void {
		// TODO: reset module-level state. Phaser already destroyed the scene's
		// game objects, tweens and this.events listeners.
	}

	/** Remove when the screen has no navigation. */
	protected goBack(): void {
		void go("title");
	}
}
`;

fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(file, template);

console.log(`Created ${path.relative(process.cwd(), file)}`);
console.log("");
console.log("Next steps:");
console.log(`  1. Add the route to Route + RouteParams in src/Scenes/routes.ts:`);
console.log(`       ${routeName}: void;`);
console.log(`  2. Register the scene in the main.ts scene list:`);
console.log(`       import { ${pascal}Scene } from "./Screens/${pascal}/${pascal}Scene";`);
console.log(`       scene: [BootScene(...), TitleScene, ${pascal}Scene]`);
console.log(`  3. Navigate with go("${routeName}") from @Scenes/AppRouter`);
