module.exports = {
	testEnvironment: "jsdom",
	transform: {
		"^.+\\.(ts|tsx)$": "ts-jest",
	},
	moduleFileExtensions: ["ts", "tsx", "js"],
	testPathIgnorePatterns: [
		"/node_modules/",
		"/e2e/",
		"\\.e2e\\.",
	],
	moduleNameMapper: {
		"^@Models/(.*)\\.js$": "<rootDir>/src/Models/$1",
		"^@Models/(.*)$": "<rootDir>/src/Models/$1",
		"^@Scenes/(.*)\\.js$": "<rootDir>/src/Scenes/$1",
		"^@Scenes/(.*)$": "<rootDir>/src/Scenes/$1",
		"^@Systems/(.*)\\.js$": "<rootDir>/src/Systems/$1",
		"^@Systems/(.*)$": "<rootDir>/src/Systems/$1",
		"^@UI/(.*)\\.js$": "<rootDir>/src/UI/$1",
		"^@UI/(.*)$": "<rootDir>/src/UI/$1",
		"^@Utils/(.*)\\.js$": "<rootDir>/src/Utils/$1",
		"^@Utils/(.*)$": "<rootDir>/src/Utils/$1",
		"^@Constants/(.*)\\.js$": "<rootDir>/src/Constants/$1",
		"^@Constants/(.*)$": "<rootDir>/src/Constants/$1",
		"^@PhaserIO$": "<rootDir>/src/phaser.io.ts",
		"^@Components/(.*)\\.js$": "<rootDir>/src/Components/$1",
		"^@Components/(.*)$": "<rootDir>/src/Components/$1",
		"^@Shaders/(.*)\\.js$": "<rootDir>/src/Shaders/$1",
		"^@Shaders/(.*)$": "<rootDir>/src/Shaders/$1",
		"^TriggerSystem/(.*)\\.js$": "<rootDir>/src/TriggerSystem/$1",
		"^TriggerSystem/(.*)$": "<rootDir>/src/TriggerSystem/$1",
		"^@i18n/(.*)\\.js$": "<rootDir>/src/i18n/$1",
		"^@i18n/(.*)$": "<rootDir>/src/i18n/$1",
		"^@lib/(.*)\\.js$": "<rootDir>/src/lib/$1",
		"^@lib/(.*)$": "<rootDir>/src/lib/$1",
		"^@Core/(.*)\\.js$": "<rootDir>/src/Core/$1",
		"^@Core/(.*)$": "<rootDir>/src/Core/$1",
		"^@Multiplayer/(.*)\\.js$": "<rootDir>/src/Multiplayer/$1",
		"^@Multiplayer/(.*)$": "<rootDir>/src/Multiplayer/$1",
		"^utils$": "<rootDir>/src/utils.ts",
		"^phaser$": "<rootDir>/src/test-utils/__mocks__/phaser.ts",
		"^(\\.{1,2}/.*)\\.js$": "$1",
	},
};
