module.exports = {
	testEnvironment: "jsdom",
	extensionsToTreatAsEsm: [".ts"],
	setupFilesAfterEnv: ["<rootDir>/src/test-utils/jest-setup.ts"],
	cacheDirectory: "<rootDir>/.cache/jest",
	transform: {
		"^.+\\.(ts|tsx)$": ["ts-jest", { useESM: true, diagnostics: false, tsconfig: { isolatedModules: true } }],
		"^.+\\.(js|jsx)$": "babel-jest",
	},
	transformIgnorePatterns: [
		"node_modules/(?!(@supabase|@jest|phaser3-rex-plugins)/)",
	],
	moduleFileExtensions: ["ts", "tsx", "js"],
	testPathIgnorePatterns: [
		"/node_modules/",
		"/dist/",
		"/supabase/",
		"/e2e/",
		"\\.e2e\\.",
	],
	moduleNameMapper: {
		"^@Models/(.*)\\.js$": "<rootDir>/src/Models/$1",
		"^@Models/(.*)$": "<rootDir>/src/Models/$1",
		"^@Screens/(.*)\\.js$": "<rootDir>/src/Client/Screens/$1",
		"^@Screens/(.*)$": "<rootDir>/src/Client/Screens/$1",
		"^@Systems/(.*)\\.js$": "<rootDir>/src/Systems/$1",
		"^@Systems/(.*)$": "<rootDir>/src/Systems/$1",
		"^@UI/(.*)\\.js$": "<rootDir>/src/UI/$1",
		"^@UI/(.*)$": "<rootDir>/src/UI/$1",
		"^@Utils/(.*)\\.js$": "<rootDir>/src/Utils/$1",
		"^@Utils/(.*)$": "<rootDir>/src/Utils/$1",
		"^@Constants/(.*)\\.js$": "<rootDir>/src/Constants/$1",
		"^@Constants/(.*)$": "<rootDir>/src/Constants/$1",
		"^@PhaserIO$": "<rootDir>/src/phaser.io.ts",
		"^@Components/(.*)\\.js$": "<rootDir>/src/Components/$1",
		"^@Components/(.*)$": "<rootDir>/src/Components/$1",
		"^@Shaders/(.*)\\.js$": "<rootDir>/src/Shaders/$1",
		"^@Shaders/(.*)$": "<rootDir>/src/Shaders/$1",
		"^TriggerSystem/(.*)\\.js$": "<rootDir>/src/TriggerSystem/$1",
		"^TriggerSystem/(.*)$": "<rootDir>/src/TriggerSystem/$1",
		"^@i18n/(.*)\\.js$": "<rootDir>/src/i18n/$1",
		"^@i18n/(.*)$": "<rootDir>/src/i18n/$1",
		"^@lib/(.*)\\.js$": "<rootDir>/src/lib/$1",
		"^@lib/(.*)$": "<rootDir>/src/lib/$1",
		"^@Core/(.*)\\.js$": "<rootDir>/src/Core/$1",
		"^@Core/(.*)$": "<rootDir>/src/Core/$1",
		"^@Multiplayer/(.*)\\.js$": "<rootDir>/src/Multiplayer/$1",
		"^@Multiplayer/(.*)$": "<rootDir>/src/Multiplayer/$1",
		"^@Data/(.*)\\.js$": "<rootDir>/src/Data/$1",
		"^@Data/(.*)$": "<rootDir>/src/Data/$1",
		"^@Game/(.*)\\.js$": "<rootDir>/src/Game/$1",
		"^@Game/(.*)$": "<rootDir>/src/Game/$1",
		"^phaser3-rex-plugins/plugins/bbcodetext-plugin\\.js$": "<rootDir>/src/test-utils/mocks/bbcodeTextPluginMock.ts",
		"^@TriggerSystem/(.*)\\.js$": "<rootDir>/src/TriggerSystem/$1",
		"^@TriggerSystem/(.*)$": "<rootDir>/src/TriggerSystem/$1",
		"^@config$": "<rootDir>/src/config.ts",
		"^@main$": "<rootDir>/src/main.ts",
		"^@assets$": "<rootDir>/src/assets.ts",
		"^@utils$": "<rootDir>/src/utils.ts",
		"^@Storage/(.*)\\.js$": "<rootDir>/src/Storage/$1",
		"^@Storage/(.*)$": "<rootDir>/src/Storage/$1",
		"^@Effects/(.*)\\.js$": "<rootDir>/src/Effects/$1",
		"^@Effects/(.*)$": "<rootDir>/src/Effects/$1",
		"^@Engine/(.*)\\.js$": "<rootDir>/src/Client/$1",
		"^@Engine/(.*)$": "<rootDir>/src/Client/$1",
		"^@test-utils/(.*)\\.js$": "<rootDir>/src/test-utils/$1",
		"^@test-utils/(.*)$": "<rootDir>/src/test-utils/$1",
		"^utils$": "<rootDir>/src/utils.ts",
		"^phaser$": "<rootDir>/src/test-utils/__mocks__/phaser.ts",
		"^Effects$": "<rootDir>/src/Effects/index.ts",
		"^(\\.{1,2}/.*)\\.js$": "$1",
	},
	collectCoverageFrom: [
		"src/Core/**/*.{ts,tsx}",
		"src/Systems/**/*.{ts,tsx}",
		"!src/**/*.d.ts",
		"!src/**/__tests__/**",
		"!src/test-utils/**",
	],
	coverageDirectory: "coverage",
	coverageReporters: ["text", "lcov", "html"],
};
